### ISSUE TITLE
wekan not working with haproxy / https

### ISSUE THREAD

**Issue by mareeba** [indiehosters/haproxy#3]
Can't seem to get the wekan docker-compose to work with haproxy. My goal is to use https with dockerized wekan just like --> https://wekan.indie.host/

Can access wekan image via http (at the specified port) but not via https.

Any advice would be most welcomed!

**wekan docker-compose** is as follows:
(domains have been removed/substituted)

```
wekandb:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128
  ports:
    - 27017

wekan:
  image: mquandalle/wekan
  links:
    - wekandb
  environment:
    - VIRTUAL_HOST=wekan.my.domain
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://wekan.my.domain
  ports:
    - 8081:80
```

**haproxy docker-compose** is as follows:

```
discovery:
  image: jwilder/docker-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./templates:/etc/docker-gen/templates"
    - "./haproxy:/etc/haproxy"
  command: "-watch /etc/docker-gen/templates/haproxy.cfg.tmpl /etc/haproxy/haproxy.cfg"
haproxy:
  image: indiehosters/haproxy
  volumes:
    - "./haproxy:/etc/haproxy"
    - "/dev/log:/dev/log"
  links:
    - letsencrypt
  ports:
    - "80:80"
    - "443:443"
letsencrypt:
  image: nginx
  volumes:
    - "./acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge:ro"
letsencrypt-watch:
  image: indiehosters/letsencrypt
  volumes:
    - "./haproxy:/etc/haproxy"
    - "./acme-challenge:/html-root/.well-known/acme-challenge/"
ocsp:
  image: indiehosters/ocsp
  volumes:
- "./haproxy:/etc/haproxy"
```
