### ISSUE TITLE
[Feature] Support IMAP/143 and SMTP/25

### ISSUE THREAD

**Issue by freechelmi** [indiehosters/haproxy#4]
I would be great to be able to use ha proxy to automatically route and SSL setup for email containers.

We could either use a special env var EMAIL_VIRTUAL_HOST

Or just ask docker gen to find the port exposed and assume that anything other than 80/443 is just TCP

**Comment by pierreozoux** [comment]
Actually, I was using StartSSL, but it is being deprecated, so I had to use let's encrypt.

You are right, one solution would be to have HAProxy in front of postfix/dovecot and handle tcp connection. We still couldn't offload TLS to HAProxy, and this would be a complicated setup.

I have a workaround to have the certs from let's encrypt, my VIRTUAL_HOST for the web of the mail server is mail.indie.host, and here is my dovecot/postfix configuration:
```
postfix:
  image: indiehosters/postfix
  hostname: "$VIRTUAL_HOST"
  environment:
    HOSTNAME: "$VIRTUAL_HOST"
  links:
    - db
    - spamassassin
    - dovecot
  volumes: 
    - ./opendkim:/etc/opendkim
    - ./TLS/dh2048.pem:/ssl/dh2048.pem
    - /system/haproxy/certs/mail.indie.host/mail.indie.host.cer:/ssl/ssl_certificate.pem
    - /system/haproxy/certs/mail.indie.host/mail.indie.host.key:/ssl/ssl_private_key.pem
    - /dev/log:/dev/log
    - ./tmp:/var/spool/postfix
  ports:
    - "25:25"
    - "587:587"
dovecot:
  image: indiehosters/dovecot
  links:
    - db
  volumes:
    - /system/haproxy/certs/mail.indie.host/mail.indie.host.cer:/ssl/ssl_certificate.pem
    - /system/haproxy/certs/mail.indie.host/mail.indie.host.key:/ssl/ssl_private_key.pem
    - ./data/dovecot/mail:/mail
    - /dev/log:/dev/log
  ports:
    - "993:993"
    - "995:995"
```

Notice how I directly mount the cert and the key from HAProxy to dovecot/postfix :)

This is the workaround for now. I close as I'll not work on it soon.
